### ISSUE TITLE
Modal alert is left aligned instead of centered

### ISSUE THREAD

**Issue by Ashley-Owens** [Ashley-Owens/TrailBlazer#12]
Steps to reproduce:
1. Clear any saved profile information
2. On the search page, enter in zip code to search for nearby trails
3. On the trails page, click the "Just for you" button to personalize trail search
4. The alert informing the user to complete a profile is left aligned instead of center aligned

Likely cause: I believe the styling on the trails.html is cascading down to the modal and affecting the alignment of the alert banner.

![Screen Shot 2020-12-01 at 10 13 14 AM](https://user-images.githubusercontent.com/54197270/100773243-d593c980-33bd-11eb-9c0b-3ecc88795cb9.png)

**Comment by liu-ronny** [comment]
Fixed in [aaea403](https://github.com/Ashley-Owens/TrailBlazer/commit/aaea403435294576fb23445fee3a97de744314e0). The div is a child of a flex container and will not take the full width of its parent by default. I fixed it by adding the Bootstrap `w-100` class to the div.
